import React, { useEffect, useRef } from 'react';
import { gsap } from 'gsap';
import { ShieldCheck, BrainCircuit, Activity, Zap } from 'lucide-react';

const Hero = () => {
  const textRef = useRef(null);
  const visualRef = useRef(null);

  useEffect(() => {
    const tl = gsap.timeline({ defaults: { ease: "power4.out" } });

    // Entry animation sequence
    tl.fromTo(textRef.current, 
      { opacity: 0, y: 40 }, 
      { opacity: 1, y: 0, duration: 1.2, delay: 0.3 }
    )
    .fromTo(visualRef.current,
      { opacity: 0, scale: 0.9 },
      { opacity: 1, scale: 1, duration: 1.5 },
      "-=0.8"
    );
  }, []);

  return (
    <section className="min-h-screen flex flex-col justify-center items-center text-center px-4 relative overflow-hidden">
      {/* Dynamic Background Neural Glow */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[400px] h-[400px] md:w-[800px] md:h-[800px] bg-fintech-accent/10 rounded-full blur-[120px] pointer-events-none animate-pulse" />
      
      <div ref={textRef} className="z-10 max-w-6xl w-full pt-20">
        {/* Feature Badge */}
        <div className="inline-flex items-center gap-2 px-4 py-2 mb-8 rounded-full border border-fintech-accent/20 bg-fintech-accent/5 backdrop-blur-xl transition-all hover:border-fintech-accent/40">
          <ShieldCheck className="w-4 h-4 text-fintech-accent" />
          <span className="text-fintech-accent text-xs font-bold uppercase tracking-[0.2em]">
            Secure Vector Analysis v2.0
          </span>
        </div>

        {/* Main Heading */}
        <h1 className="text-5xl md:text-8xl font-black tracking-tighter mb-8 leading-[1.1]">
          Financial Intelligence <br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-fintech-accent via-blue-400 to-purple-500">
            Beyond Numbers.
          </span>
        </h1>

        {/* Subtext */}
        <p className="text-lg md:text-xl text-gray-400 mb-16 max-w-2xl mx-auto leading-relaxed font-medium">
        Turn your UPI transactions into clear financial insights.”
        </p>

        {/* --- PROJECT CONTENT NODES --- */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-left max-w-5xl mx-auto mb-10">
          <FeatureNode 
            icon={<BrainCircuit className="text-fintech-accent" />}
            title="Predictive Forecasting"
            desc="ML-driven regression models analyze historical burn rates to forecast next-month liquidity with high precision."
          />
          <FeatureNode 
            icon={<Zap className="text-purple-400" />}
            title="Grok AI Insights"
            desc="Contextual financial advice generated by ML logic based on your unique categorized spending habits."
          />
          <FeatureNode 
            icon={<Activity className="text-emerald-400" />}
            title="Risk Detection"
            desc="Anomaly detection algorithms flag unusual high-value transactions or suspicious patterns using Z-score analysis."
          />
        </div>
      </div>

      {/* Decorative Neural Grid Overlay */}
      <div ref={visualRef} className="absolute bottom-0 w-full h-1/2 opacity-20 pointer-events-none">
        <div className="absolute inset-0 bg-gradient-to-t from-fintech-primary via-transparent to-transparent z-10" />
        <div className="w-full h-full border-t border-white/5 grid grid-cols-12 gap-4 px-4">
          {[...Array(12)].map((_, i) => (
            <div key={i} className="h-full border-x border-white/5" />
          ))}
        </div>
      </div>
    </section>
  );
};

/* Reusable Feature Component */
const FeatureNode = ({ icon, title, desc }) => (
  <div className="bg-white/5 border border-white/5 p-6 rounded-3xl backdrop-blur-sm hover:border-white/10 transition-all group">
    <div className="w-12 h-12 rounded-2xl bg-white/5 flex items-center justify-center mb-5 group-hover:scale-110 transition-transform">
      {icon}
    </div>
    <h3 className="text-white font-bold text-xl mb-3">{title}</h3>
    <p className="text-gray-500 text-sm leading-relaxed">{desc}</p>
  </div>
);

export default Hero;